- .dockerignore
- Dockerfile
- docker-compose.yaml
* Add minimal docker files for development
```
git clone https://github.com/uwcirg/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY
cd AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY
docker-compose build
docker-compose up
```
[Open modified launch URL](https://launch.smarthealthit.org/launcher?launch_uri=http%3A%2F%2Flocalhost%3A8000%2Flaunch.html&patient=5c41cecf-cf81-434f-9da7-e24e5a99dbc2%2C417c9b95-6af1-4025-882a-32d8ccf05366&fhir_ver=2)
> Add Docker files

- src/components/Header.js
fix src reference to AHRQ logo image
> fix image src reference

- src/components/ExclusionBanner.js
- src/components/InclusionBanner.js
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
- src/cql/valueset-db.json
Updated the R4 Factors_... and InclusionBanner to remove all exclusion criteria except being over 18.
Updated the R4 Factors_ to include overdoses as a risk factor condition
Updated the R4 Factors_ with increased prescription lookback range from 2 to 100 years
Updated ExclusionBanner to include inpatient treatment
Updated valueset-db with opioid overdose codes
> Updated R4 CQL and related documents.

- src/components/summary.json
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
- src/cql/valueset-db.json
Updated relevant files to include carisoprodol.
> Md02242020

- src/cql/dstu2/Factors_to_Consider_in_Managing_Chronic_Pain.cql
- src/cql/dstu2/Factors_to_Consider_in_Managing_Chronic_Pain.json
Updated the CQL for R2, in case folks want that.
> Updated CQL (and thus JSON ELM) for R2

- public/ocupacion.json
- src/components/DataInfo.js
- src/components/Landing.js
- src/components/Summary.js
- src/components/summary.json
- src/styles/components/_Summary.scss
- Retrieve occupational health data via hard-coded JSON
- add datasource information for occupational health data
- add code to allow dynamic display of sections via Summary.json
- remove hard-coded code to display sections
- minor styling fixes
> Occupation Health section frontend updates

- src/components/Landing.js
- src/components/Summary.js
- src/components/summary.json
- src/styles/components/_Summary.scss
- src/styles/elements/_variables.scss
Fix section orders
Add different flag colors for WA vs CDC guidelines
[Launch URL for this Pull Request](https://launch.smarthealthit.org/launcher?launch_uri=https%3A%2F%2Fdeploy-preview-15--distracted-jepsen-bc9c39.netlify.com%2Flaunch.html&patient=525005&fhir_ver=4)
> Summary display updates

- src/components/summary.json
[Launch URL for this Pull Request](https://launch.smarthealthit.org/launcher?launch_uri=https%3A%2F%2Fdeploy-preview-16--distracted-jepsen-bc9c39.netlify.com%2Flaunch.html&patient=525039&fhir_ver=4)
> switch pmp meds and ehr meds order

- src/components/ExclusionBanner.js
> edited exclusion banner to match DOH wording

- src/components/DataInfo.js
- src/components/Landing.js
- src/components/Summary.js
- src/components/summary.json
- src/styles/components/_Summary.scss
- src/styles/elements/_variables.scss
Explicit display error message when loading of external dataset, such as that from PDMP fails.
[Launch URL for this Pull Request](https://launch.smarthealthit.org/launcher?launch_uri=https%3A%2F%2Fdeploy-preview-20--distracted-jepsen-bc9c39.netlify.com%2Flaunch.html&patient=5c41cecf-cf81-434f-9da7-e24e5a99dbc2&fhir_ver=4)
addressing stories:  https://www.pivotaltracker.com/story/show/172483336  and https://www.pivotaltracker.com/story/show/172483471
> External data error display update and load fake data

- src/components/ExclusionBanner.js
- src/components/Landing.js
- src/components/Summary.js
- src/components/graph/MMEGraph.js
- src/styles/components/_Summary.scss
- src/styles/elements/_banners.scss
- src/styles/elements/_tables.scss
- src/styles/elements/_variables.scss
- update alert displays to add link to sections
- allow warning notice to be re-viewable
- overview panel styling fixes
[Launch URL](https://deploy-preview-26--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> Overview panel alerts update

- src/components/Summary.js
- src/components/summary.json
- src/styles/components/_Summary.scss
- src/styles/elements/_banners.scss
- src/styles/elements/_tables.scss
- add tooltip text to side navigation close button
- update MME references to MED in summary.json file
[Launch URL](https://deploy-preview-27--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> navigation tooltip fixes, MED text update, styling updates

- src/__tests__/components/Summary.test.js
- src/__tests__/helpers/flagit.test.js
- src/components/Header.js
- src/components/Landing.js
- src/components/Summary.js
- src/components/summary.json
- src/styles/components/_Summary.scss
- Fix broken tests: For summary, landing and flagit help tests
- simplify code for returning section entry counts
[launch URL](https://deploy-preview-28--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> fix broken tests

- src/__tests__/helpers/flagit.test.js
- src/components/Landing.js
- src/components/Summary.js
- src/components/graph/MMEGraph.js
- src/components/summary.json
- src/helpers/flagit.js
- src/styles/components/_Summary.scss
per this story: 
https://www.pivotaltracker.com/story/show/172687021
[Launch URL](https://deploy-preview-29--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> Risk overview alerts update

- src/components/Summary.js
- src/components/graph/MMEGraph.js
- src/components/graph/line.js
- src/components/summary.json
- src/styles/components/_Summary.scss
add data points to MME graph
[launch URL](https://deploy-preview-30--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> minor MED graph adjustments - add data points

- src/components/graph/line.js
add labels to data points on MED graph
[Launch URL](https://deploy-preview-31--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> add label to data point in MED graph

- src/components/Landing.js
- src/components/Summary.js
- src/components/summary.json
- src/helpers/flagit.js
- src/styles/components/_Summary.scss
Update displays of alert text and guideline text
- remove alert icon next to guideline text in section to decrease confusion regarding its relation to flag text
- remove color coding legend related to Washington & CDC guidelines to decrease confusion
[Launch URL](https://deploy-preview-32--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> update displays of flag text and guideline text

- public/assets/data/patientEducationReferences.json
- src/components/Landing.js
- src/components/summary.json
- src/helpers/formatit.js
- src/styles/components/_Summary.scss
addressing this story: https://www.pivotaltracker.com/story/show/173023533
add display of file type and size to each patient education resource link (where applicable).
[Launch URL ](https://deploy-preview-33--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> update display of patient education section

- src/components/Landing.js
- src/components/Summary.js
- src/components/summary.json
- src/helpers/flagit.js
- src/styles/components/_Summary.scss
modified dashboard to display plain risk factor language. 
Also added one overlooked section to summary.json (opioid overdose - should not have any visible changes)
[Launch URL](https://deploy-preview-34--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> Modified alerts with plain language

- src/components/graph/MMEGraph.js
- src/styles/components/_Summary.scss
[Launch URL](https://deploy-preview-36--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> address graph layout in IE

- public/index.html
- public/js/index.js
address : https://www.pivotaltracker.com/story/show/173402112
adding frontend code to read config variables in generated json file (if exists) for use by frontend
> react runtime config: frontend changes

- src/styles/components/_Summary.scss
- src/styles/elements/_variables.scss
[Launch URL](
https://deploy-preview-37--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> fix background color for at a glance box

- src/components/summary.json
- src/styles/components/_Header.scss
- src/styles/components/_Summary.scss
- src/styles/elements/_modal.scss
- src/styles/elements/_tables.scss
address:
https://www.pivotaltracker.com/story/show/173617597
https://www.pivotaltracker.com/story/show/173617686
minor styling fixes to graph, modal to address layout issues seen in IE
fix Non-Opioid Medications section title to Non-Opioid Pain Medications
[Launch URL](
https://deploy-preview-46--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> styling fixes, title change for non-opioid meds section

- src/components/graph/MMEGraph.js
- sort date in ascending order to insure that data line will draw correctly 
- add fix to account for minimum and maximum interval data points for data set with range small than the initial set number of intervals
[Launch URL](
https://deploy-preview-47--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> Graph updates

- src/styles/components/_Summary.scss
Fix graph size in larger screen width.
[Launch URL](
https://deploy-preview-49--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> fix graph responsive sizes in larger browser widths

- src/components/summary.json
address https://www.pivotaltracker.com/story/show/173955564
add guideline text for Carisoprodol meds section
[Launch URL](https://launch.smarthealthit.org/launcher?launch_uri=https%3A%2F%2Fdeploy-preview-52--distracted-jepsen-bc9c39.netlify.com%2Flaunch.html&patient=5c41cecf-cf81-434f-9da7-e24e5a99dbc2&fhir_ver=4)
> carisoprodol meds guideline text update

- src/components/Landing.js
- src/components/Summary.js
- src/styles/components/_Summary.scss
- move guideline rendering code to a function
- add null checks for patient and summary data
- guideline content styling fixes
[Launch URL](https://launch.smarthealthit.org/launcher?launch_uri=https%3A%2F%2Fdeploy-preview-53--distracted-jepsen-bc9c39.netlify.com%2Flaunch.html&patient=5c41cecf-cf81-434f-9da7-e24e5a99dbc2&fhir_ver=4)
> update guideline text function, styling fix

- src/utils/r4_test_patients/darth_vader.json
- src/utils/r4_test_patients/padme_amidfla.json
* Add **Darth Vader** and **Padme Amidfla** test patients
* Use Brenda as a template, overwrite with PDMP data
* Remove PDMP MedicationRequests copied as EHR meds
> PDMP Test Patients

- src/utils/executeELM.js
Fix get EPIC query environment variable issue in executeElm function
Add a debugging statement to see what bundles are actually being fetched
> fix get env issue in executeElm

- src/utils/envConfig.js
- src/utils/executeELM.js
Fix retrieval of config variables
> Test configs

- src/components/Summary.js
- src/styles/components/_Summary.scss
- src/utils/envConfig.js
- src/utils/executeELM.js
- add icon back for Education Material
- minor styling fix for when no graph data is present
- add check for null entry when fetching bundle data for patient
[Launch URL](https://launch.smarthealthit.org/launcher?launch_uri=https%3A%2F%2Fdeploy-preview-64--distracted-jepsen-bc9c39.netlify.com%2Flaunch.html&patient=5c41cecf-cf81-434f-9da7-e24e5a99dbc2&fhir_ver=4)
> Minor ui education changes

- src/components/Landing.js
- src/components/graph/MMEGraph.js
- src/components/graph/line.js
- src/components/summary.json
Fix MME graph to indicate daily MME value
> MME graph rendering fix

- default.env
- src/components/AlertBanner.js
- src/components/DevTools.js
- src/components/Header.js
- src/components/Landing.js
- src/components/Summary.js
- src/components/graph/MMEGraph.js
- src/components/graph/line.js
- src/components/summary.json
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
- src/cql/r4/MMECalculator.cql
- src/cql/r4/MMECalculator.json
- src/cql/r4/OMTKLogic.cql
- src/cql/r4/OMTKLogic.json
- src/cql/valueset-db.json
- src/elements/Spinner.js
- src/helpers/formatit.js
- src/styles/App.scss
- src/styles/components/_Header.scss
- src/styles/components/_Summary.scss
- src/styles/elements/_banners.scss
- src/styles/elements/_base.scss
- src/styles/elements/_button.scss
- src/styles/elements/_spinner.scss
- src/styles/elements/_variables.scss
- src/utils/executeELM.js
- src/utils/r4_test_patients/brenda_jackson.json
address:
https://www.pivotaltracker.com/story/show/178493646
https://www.pivotaltracker.com/story/show/178474396
- new patient research button (click event will: clear sessionStorage and go to patient search url obtained via **FEMR_BASE_DOMAIN** variable set **envs.json**)  see screenshot: 
- add loading message to loading spinner screen to include number of resources being loaded
- add additional information to Medication Request CQL (strength, daily dose, factor) for better debugging
- fix CQL code to return correct daily dose for Fentanyl & Buprenorphine patches
-  Add MME column to the PDMP Prescriptions section
[Preview](https://launch.smarthealthit.org/launcher?launch_uri=https%3A%2F%2Fdeploy-preview-74--distracted-jepsen-bc9c39.netlify.com%2Flaunch.html&patient=5c41 …
> new patient search button && loading message

- .github/workflows/docker-cd.yaml
- Dockerfile
- docker-compose.yaml
Add VCS-based version string to docker build process
> Configure VCS-based version

- src/components/ErrorBanner.js
- src/components/Landing.js
- src/components/Summary.js
- src/elements/Version.js
- src/styles/components/_Summary.scss
- src/styles/elements/_banners.scss
- src/styles/elements/_base.scss
- src/styles/elements/_tables.scss
- src/styles/elements/_version.scss
part of this story:  https://www.pivotaltracker.com/story/show/178610677
- display error, e.g. when server raised 500 error when retrieving resources, on UI when applicable
- fix React warning errors related to Version component, i.e. allow version string to be number or string, fix className attribute
> add error display to UI when applicable

- .github/workflows/docker-cd.yaml
- Remove semantic versioning config
- Create docker image tags to match git tags (previously assumed working)
> Cleanup CI/CD

- src/components/Landing.js
- src/components/Summary.js
- src/components/Warning.js
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
- src/styles/elements/_banners.scss
Address: https://www.pivotaltracker.com/story/show/178887243
remove age restriction for inclusion criteria
> Age inclusion criteria update

- src/components/Landing.js
- src/components/Summary.js
Address: https://www.pivotaltracker.com/story/show/178939495
Frontend code changes to hide section(s) or sub-section(s) via environment variables
> hide section (and or sub-sections) via environment variables

- src/components/graph/MMEGraph.js
https://www.pivotaltracker.com/story/show/178560025
Per feedback, update error message displayed to user
> mme graph error message update

- src/components/summary.json
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
- src/helpers/formatit.js
Address https://www.pivotaltracker.com/story/show/179245557
Add drug class column to PDMP Medications section
> add drug class column to PDMP Meds section

- src/components/Landing.js
Update patient search URL, i.e. `/clear_session`
> update patient search url

- src/components/Landing.js
fix back to patient search URL when page loads on error
> fix patient search url on page error

- src/components/Landing.js
as per [conversation](https://cirg.slack.com/archives/C01P9V67NMA/p1631313591199800)
display error for opioid medication(s) whose MME wasn't calculated
> display error for opioid

- src/components/summary.json
text updates based on feedback for this story: https://www.pivotaltracker.com/story/show/179677040
> update alert texts for benzo, caripsoprodol and sedatives

- src/components/summary.json
Add dispensed date to sedative/barbiturate alerts per feedback
part of https://www.pivotaltracker.com/story/show/179677040
> add dispensed date to sedative/barbiturate alerts

- src/components/summary.json
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
per feedback from story: https://www.pivotaltracker.com/story/show/179677040
add missing field information, e.g. prescriber and pharmacy for benzo, sedative and meds
> add missing fields (e.g. prescriber) for benzo, sedative and bartiturates

- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
Add missing quantity field to barbiturates meds
> add missing quantity field to bartiburate meds

- src/components/Landing.js
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
The graph errors out when fed with a value that is not a number.
This fix intends to address that - not include null MME value when drawing graph
> fix graph issue when fed with non-number MME value

- src/utils/executeELM.js
part of https://www.pivotaltracker.com/story/show/180042213
> add no cache header when making FHIR API request

- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
part of https://github.com/uwcirg/cosri-patientsearch/pull/97
display urine screen lab, if any, from Quest Diagnostics (used by Kent site)
> UDS for Kent

- src/components/Landing.js
- src/styles/elements/_base.scss
- src/styles/elements/_spinner.scss
- src/styles/elements/_variables.scss
- src/utils/executeELM.js
Address https://www.pivotaltracker.com/story/show/179860790
Instead of number of resources loaded, display the actual items being loaded (using FHIR resource type for each resource) in progress status
> update progress status display to include items being loaded

- src/components/Landing.js
- src/components/Summary.js
- src/components/summary.json
- src/styles/components/_Header.scss
- src/styles/components/_Summary.scss
- src/styles/elements/_base.scss
- src/styles/elements/_tables.scss
- src/styles/elements/_variables.scss
https://www.pivotaltracker.com/story/show/179860775
https://www.pivotaltracker.com/story/show/179860784
- In Patient Risk Overview sections: there are now three panels one for graph, one for rx summary and one for alerts
- Adding stats for Rx by drug class in the rx summary panel
Example screenshot:
> Overview panel layout, stats updates

- src/components/Landing.js
When display MME calculation error, display ONLY one per medication
See story https://www.pivotaltracker.com/story/show/180592106
> MME calc error display - do not display same med twice

- src/components/Landing.js
When display MME calculation error, display ONLY one per medication
> Revert "MME calc error display - do not display same med twice"

- src/components/Summary.js
- src/components/summary.json
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
- src/styles/components/_Summary.scss
part of https://www.pivotaltracker.com/story/show/179860582
- new section titled, **Controlled Substance Agreement**, just below the Urine Tox Screen section
- alert will display if a controlled substance agreement is due for this patient on or before 3 or 4 months of next due date
- alert will display if more than a year has passed since the last controlled substance agreement was signed
- alert will display if there is no controlled substance agreement with this patient
> new CS agreement section

- public/assets/data/providerEducationReferences.json
https://www.pivotaltracker.com/story/show/181485419 
Wording fix per feedback
> provider resource - wording fix

- .github/workflows/test.yaml
- src/__tests__/components/ExclusionBanner.tests.js
> Run unit tests in CI

- src/components/Report/components/RankedResponses.js
- src/components/Report/components/ResponsesSummary.js
Add copy button to the Goals & Expectations section.
See screenshot:
> add copy button to Goals & Expectations section

- src/components/Landing/index.js
Remove unused function parameter and null variable when combining objects
> Landing: fix params

- src/components/Landing/index.js
- src/helpers/timeout.js
- src/helpers/utility.js
- make functions `getTokenInfoFromStorage`, `parseJwt` accessible to components
- add helper functions to return `REACT_APP_DASHBOARD_URL` environment variable
- add helper function to return patient search URL
- add check for access token before processing summary data
> add check for access token before processing summary data

- src/components/Report/components/RankedResponses.js
- src/styles/elements/_tables.scss
- fix check for selected index for nav buttons
- increase padding for buttons for ease of click/touch
- table formating fix
> Goals & Expectations - follow up fixes, navigation and table styling

- src/components/graph/ReportOverviewGraph.js
- src/styles/elements/_slider.scss
Fix graph slider label styles when rotated
> fix slider label styles

- src/components/Landing/index.js
- src/components/Landing/utility.js
- src/components/Summary.js
- src/elements/Version.js
- src/helpers/timeout.js
- src/helpers/utility.js
- src/launch.js
- src/styles/elements/_banners.scss
- src/styles/elements/_button.scss
- src/styles/elements/_slider.scss
- src/utils/envConfig.js
- src/utils/executeELM.js
- lint/format code
- add helper functions for retrieving environment variables to reduce code repetition
> linting code, refactor repetitive code related to getEnv

- src/components/graph/ReportOverviewGraph.js
- src/utils/executeELM.js
Reset date range to max of all selected questionnaires when new one is added or removed on graph
> report graph - reset date range when selecting/add new questionnaire

- src/components/Report/components/ScoringSummary.js
- src/components/Report/index.js
- src/config/report_config.js
make sure casing on anchor id for each section matches in order for scrolling to the target section works.
> report - fix section anchor ids

- src/components/Report/components/Overview.js
- src/components/Report/components/ScoringSummary.js
- src/components/Report/index.js
- src/components/Report/utility.js
followup fix to #178 
- fix check for no report data as report data contains object with nested loops
> fix no reportable data check

- src/styles/elements/_banners.scss
> fix info icon styling in banner

- src/components/Report/components/ResponsesSummary.js
- src/styles/elements/_tables.scss
fix row header border styles (see screenshot after fixes):
> table row headers - fix styles

- src/components/Report/components/Table.js
- src/components/SideNav.js
- src/components/Summary.js
- src/styles/components/_Report.scss
- allow tooltip to show on mobile devices (e.g. ontouch/click event)
- minor table styling fix (copy button location fix)
> tooltip mobile device fix, table styling fix

- src/styles/components/_Header.scss
- src/styles/components/_Summary.scss
- src/styles/elements/_modal.scss
- src/styles/elements/_tabs.scss
- src/styles/elements/_variables.scss
header, nav, tabs styling fixes
> nav, header styling fixes

- src/styles/elements/_banners.scss
- src/styles/elements/_button.scss
- src/styles/elements/_tabs.scss
tab styling fix
- inactive tab color and background color update
- slight tab shape fix
- fix hover state, casing to be consistent with other interactive elements
> tab styling fix

- src/styles/components/_Summary.scss
Fix data info color on hover - to be consistent with other button/links
> fix data info link hover css

- src/styles/elements/_tables.scss
to have color and background color consistent with that of other buttons/links on the page
> fix styling of pagination buttons/inputs

- src/styles/elements/_tables.scss
> pagination button styling fixes

- src/components/SideNav.js
- src/components/graph/ReportOverviewGraph.js
- src/styles/elements/_slider.scss
- fix overlapped text display
- rotate text as needed
> report graph scale display fixes

- src/components/graph/ReportOverviewGraph.js
- src/styles/elements/_slider.scss
fix styling when scale units are rotated.
> fix scale styling

- src/components/Landing/utility.js
- src/components/Summary.js
- src/config/summary_config.json
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
- src/helpers/flagit.js
- src/styles/components/_Summary.scss
- src/styles/elements/_variables.scss
https://www.pivotaltracker.com/story/show/188376552
An alert (preceded by bloo exclamation icon) for naloxone prescription if:
- MME >= 50
- No Naloxone prescription on the last 12 months
Screenshot of the changes:
> Add Naloxone Prescription Alert

- src/components/Landing/index.js
report tab index is 1, overview tab index is 0.
> fix index check for report tab

- src/config/report_config.js
part of https://www.pivotaltracker.com/story/show/188409745
Add department for procedure, referrals.
Screenshot after change:
> add ordering department column to procedures

- src/helpers/utility.js
Update check for enabling report tab to include check for demo site id
> fix check for enabling report tab

- src/components/Report/components/BodyDiagram.js
- src/components/Report/components/ResponsesSummary.js
- src/components/Report/components/ScoringSummary.js
- src/styles/components/_Header.scss
- src/styles/components/_Report.scss
- src/styles/components/_Summary.scss
- src/styles/elements/_tables.scss
- src/styles/elements/_tabs.scss
Address https://app.shortcut.com/cirg/story/2076/cosri-report-tab-responsive-layout-issue-s-for-some-patients-data-conditions
address Report tab layout issue in mobile device browser size
example screenshots after fix:
> report responsive styling fixes

- src/utils/executeELM.js
see PR #227
This one is based off of the `main` branch
> no-cache request header fix

- src/components/graph/MMEGraph.jsx
per [Slack convo](https://cirg.slack.com/archives/C01P9V67NMA/p1754091660786269):
change MME graph title to Morphine Milligram Equivalents (MME) 
Screenshot:
> change MME graph title as requested
