- Dockerfile
- Dockerfile.production
- default.env
- docker-compose.yaml
- frontend.env.default
- src/launch.js
* Read launch context (and `fakeTokenResponse`) from back-end, if configured
* Move docker configuration into `.env` 
* NB: values in `frontend.env` must be moved to `.env`
* Add production Dockerfile
> Backend Authentication

- src/components/Landing.js
Found a bug where demo data is presented even when PDMP endpoint is returning legitimate data.
Fix is to read response stream into a JSON object (JSON.parse does not work on a Response object).
> fix parsing of response stream

- package.json
- src/index.js
address @babel/polyfill deprecation warning - remove dependency on deprecated @babel/polyfill library and use react-app-polyfill libraries instead
[Launch URL](https://deploy-preview-35--distracted-jepsen-bc9c39.netlify.app/launch?launch=eyJhIjoiMSIsImIiOiI0MTcwMiJ9&iss=https%3A%2F%2Fsmart-dev-sandbox-launcher.cirg.washington.edu%2Fv%2Fr2%2Ffhir)
> use react polyfill library, remote dependency on deprecated babel polyfill library

- public/assets/data/PDMPDemoData.json
- src/components/Landing.js
- src/components/summary.json
- src/launch.js
- src/styles/components/_Summary.scss
- src/utils/envConfig.js
Issues addressed in this PR:
- read env.JSON file into global window variables that can be accessed by application and won't be overridden when Node initializing and processing env variables.
- fix bug raised due to change in PDMP Medication json structure
- add patient id as query parameter to get PDMP medications
- update demo data to be loaded (data with updated JSON structure) when call to API failed (TODO, load demo data only in demo environment)
> env variables retrieval, medication list bug fix and patient id updates

- src/components/Video.js
- src/elements/Iframe.js
address https://www.pivotaltracker.com/story/show/173475110 
Fix include:
Loading patient education video only when needed - as when user clicks like to see the video
> Lazy load education video

- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
- src/cql/r4/MMECalculator.cql
- src/cql/r4/MMECalculator.json
- src/utils/r4_test_patients/brenda_jackson.json
Fix doseQuantity calculation in MME Calculator CQL
1.  update code to look for `dosageInstruction . doseAndRate . doseQuantity ` for doseQuantity in a MedicationRequest
2.  if 1. is not present, calculate doseQuantity by  `dispense quantity / expected supply duration`
3. add example MedicationRequests to Brenda Jackson  patient JSON for testing
[Preview](https://launch.smarthealthit.org/launcher?launch_uri=https%3A%2F%2Fdeploy-preview-70--distracted-jepsen-bc9c39.netlify.com%2Flaunch.html&patient=5c41cecf-cf81-434f-9da7-e24e5a99dbc2&fhir_ver=4)
> fix doseQuantity calculator in MME Calculator

- src/components/Warning.js
- src/styles/elements/_banners.scss
Address https://www.pivotaltracker.com/story/show/178887243
Update stylings for the warning message presented for underage patient 
change background color to red
bold the warning text
> fix underage warning message stylings

- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
- src/cql/r4/MMECalculator.cql
- src/cql/r4/MMECalculator.json
- src/cql/r4/OMTKLogic.cql
- src/cql/r4/OMTKLogic.json
Address: https://www.pivotaltracker.com/story/show/178935354
Provide default values for dose quantity and/or doses per day for MME calculator **if** they are missing from Medication Request JSON from the backend.  NOTE, these are fallback calculations.  Dose quantity information from a FHIR endpoint, e.g. confidential backend, will always be used first if present.
- provide default of doseQuantity of 1.0 (see [FHIR specs](https://www.hl7.org/fhir/dosage-definitions.html#Dosage.doseAndRate.dose_x_))
- provide default calculated daily dose, i.e. supplyQuantity / supplyDuration, if frequency and period is missing from the Medication Request JSON.
Current calculations done in confidential back can be seen [here](https://github.com/uwcirg/sof-api-wrapper/blob/e2add2dcbb78d4d273 …
> Mme calculator defaults updates

- src/cql/valueset-db.json
Per https://docs.google.com/spreadsheets/d/1WhUqBodmQnO5t1JMxy_3vxGcKN037qwm/edit#gid=1608355322
Add rxnorms for opioid medications missing from the valueset db
> add missing rxnorms for opioid meds to valueset

- src/cql/r4/OMTKLogic.cql
- src/cql/r4/OMTKLogic.json
Address null conversion factor returned for methadone (ingredient code of  `6913`)
For methadone, conditional comparison of daily dose to determine conversion factor fails when daily dose **is not** integer (e.g. 4.0476190476190474)
Fix is to add operator, Ceiling, that will return the first integer greater than or equal to its argument, in the comparison
> fix null conversion factor issue for methadone

- src/components/summary.json
Per feedback, update WA guideline text for benzodiazepine medications, sedatives, barbiturates and caripsoprodol medications
See https://drive.google.com/file/d/1uXTgGUAsiqI2MuZ9YS0CMf3OzL3KsIkF/view
> update WA guideline text for benzo, sedatives, barbiturates and caripsoprodol

- src/components/Landing.js
Address syntax error that exits the loop prematurely for checking whether a section of a summary should be hidden
> bugfix - address syntax error for hiding section(s) in summary

- src/components/Header.js
- src/components/Landing.js
- src/styles/components/_Header.scss
- src/styles/elements/_variables.scss
Address https://www.pivotaltracker.com/story/show/180606339
Patient name is cut off in header due to logo size
Fix includes:
- increase header size
- adjust styling for div element containing patient name
Example output after fix
> header - fix patient name cutoff issue as seen in Kent Prod 

- .github/workflows/docker-cd.yaml
- Remove DockerHub as secondary image registry
- Only merge after uwcirg/cosri-pain-management-summary/pull/150, once every *-environments repo is using GHCR (instead of DockerHub)
> Remove DockerHub

- src/components/ExclusionBanner.js
- src/components/graph/MMEGraph.js
- src/styles/elements/_banners.scss
- src/styles/elements/_base.scss
- src/styles/elements/_button.scss
Per [Slack convo](https://cirg.slack.com/archives/C01P9V67NMA/p1723055082632559)
- remove CDC avoid/justify threshold line (at 99mme)
- re-label CDC extra precautions threshold (at 50 mme) to "CDC: consider offering naloxone"
- re-label WA state threshold to "WA State:  Consultation Threshold"
(see screenshot)
- update limitation text (see screenshot)
collapased view: 
expanded view:
> add CDC related text changes

- src/components/Summary.js
found while testing that the go to section links  in the alert panel (see screenshot) are no longer working.
Fix include:
- add back the anchor link containing the `name` and `href attributes
> anchor link fix

- src/components/Report/index.js
- src/config/report_config.js
For sections rendering questionnaire responses, use title provided in FHIR Questionnaire json if present.  The title provided in `report_config` is the default.
> section title - use questionnaire title if applicable

- src/styles/elements/_tables.scss
Increase width of first column for responses table with two columns (see screenshot after changes):
> minor table styling fix

- src/styles/elements/_tables.scss
add chevron arrows to pagination buttons, to be consistent with other nav buttons on page
> pagination buttons - add chevron arrows

- src/cql/r4/OMTKLogic.cql
- src/cql/r4/OMTKLogic.json
See [Slack convo](https://cirg.slack.com/archives/C01P9V67NMA/p1728510815717779)
Change conversion factors:
-  Hydromorphone (from 4 to 6)
- Tramadol (from 0.1 to 0.2)
- Buprenorphine transdermal patch (from 1.8 X 7 = 12.6 to 2.2 X 7 = 15.4 )
Screenshot (using Buprenorphine):
> update conversion factors for tramadol and hydromorphone

- src/styles/components/_Report.scss
https://www.pivotaltracker.com/story/show/188476035
Fix Questionnaire Responses table display issue.
Before fix
After fix
> responses table overflow display issue

- src/components/Summary.js
- src/components/graph/MMEGraph.js
- src/styles/components/_Summary.scss
- Fix spacing between legend and graph
- Fix legend orphan text, i.e. o in "w/o" text
screenshot before fix:
screenshot after fix:
> MME Graph - spacing, legend styling fixes

- src/config/summary_config.json
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql
- src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.json
- src/helpers/flagit.js
Per [Slack convo](https://cirg.slack.com/archives/C01P9V67NMA/p1732298819947879)
Display naloxone alert for opioid meds (non-buprenorphine) that the patient is currently taking (as of today)
**screenshot for when the user is currently taking opioid:**
**screenshot for when the user is not currently taking opioid (no alert):**
> fix naloxone alert for active opioid meds  only

- src/components/Summary.js
- src/config/report_config.js
- src/styles/components/_Summary.scss
- src/utils/executeELM.js
per [Slack convo](https://cirg.slack.com/archives/C01P9V67NMA/p1733356402568939)
- Allow more graceful handling of error when processing questionnaire ELM lib, i.e. use default lib as specified without raising exception.
- Will not halt on exception anymore in FF
Other fix:
- minor styling fix of error display
> handle error when survey has not associated ELM lib

- src/components/Landing/index.js
- src/helpers/utility.js
Address https://www.pivotaltracker.com/story/show/188705822
- Add user info to each event logging
- Add `analytics` tag to tab/open/view events
- Prevent `cosri-frontend` tag from being added multiple times
Example JSONs posted
```
{
"patient": "Barney Abbott",
"message": "MME calculated: Name: Fentanyl Transdermal System, 0.05 mg/hr...",
"level": "info",
"tags": ["mme-calc", "cosri-frontend"],
"patientName": "Barney Abbott",
"subject": "Patient/5ee05359-57bf-4cee-8e89-91382c07e162",
"user": { "username": "amysbubble" }
}
```
```
{
"patient": "Barney Abbott",
"message": "overview tab",
"level": "info",
"tags": ["tab", "analytics", "cosri-frontend"],
"patientName": "Barney Abbott",
"subject": "Patient/5ee05359-57bf-4cee-8e89-91382c07e162",
"user": { "username": "amysbubble" }
}
```
> Frontend logging fixes

- .github/workflows/docker-cd.yaml
elgohr/Publish-Docker-Github-Action@master is not supported anymore
> Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)

- src/utils/executeELM.js
per [convo](https://cirg.slack.com/archives/C01P9V67NMA/p1744844940353289?thread_ts=1744676274.124889&cid=C01P9V67NMA) in Slack
- Set `_count` ([number of resources per page](https://build.fhir.org/search.html#count)) for QuestionnaireResponse to 300 to reduce the amount of HTTP requests
- Set `_count` to 50 for other FHIR resources (and their additional page requests)
> set initial counts for requests

- src/components/DevTools.jsx
- src/components/Disclaimer.jsx
- src/components/ErrorBanner.jsx
- src/components/Landing/index.jsx
- src/components/Report/index.jsx
- src/components/Summary.jsx
- src/config/summary_config.json
- src/config/tocbot_config.js
- src/elements/Spinner.jsx
- src/styles/components/_Report.scss
- src/styles/components/_Summary.scss
- src/styles/elements/_banners.scss
- src/styles/elements/_tabs.scss
- src/utils/executePainFactorsELM.js
- src/utils/executeReportELM.js
- vite.config.mjs
Part of the [story](https://app.shortcut.com/cirg/story/2132/review-uw-prod-with-front-end-tools-to-identify-performance-bottlenecks)
- code changes to delay firing off HTTP requests for FHIR resources for Report, i.e. after resources for the Overview tab have been loaded - this will reduce the number of HTTP requests for FHIR resources on initial page load to reduce load time
code changes include:
- extract out code related to extracting and executing Report resources from `executeELM.js`  to separate js file, i.e. `executeReportELM.js`
- move code for initializing tocbot to separate JS file for re-usability purpose 
- add cleanup code for when a component is un-mounted, e.g. remove event listener, clear timer intervals, to prevent memory leak
> Update handling of report resource requests
